apiVersion: v1
kind: Secret
metadata:
  name: togglemaster-secrets
  namespace: togglemaster
type: Opaque
stringData:
  AUTH_DATABASE_URL: postgres://togglemaster:<SENHA_RDS>@togglemaster-auth-db.cknqp4egvwvw.us-east-1.rds.amazonaws.com:5432/auth_db?sslmode=require
  FLAG_DATABASE_URL: postgres://togglemaster:<SENHA_RDS>@togglemaster-flag-db.cknqp4egvwvw.us-east-1.rds.amazonaws.com:5432/flags_db?sslmode=require
  TARGETING_DATABASE_URL: postgres://togglemaster:<SENHA_RDS>@togglemaster-targeting-db.cknqp4egvwvw.us-east-1.rds.amazonaws.com:5432/targeting_db?sslmode=require
  MASTER_KEY: <MASTER_KEY_ADMIN>
  SERVICE_API_KEY: tm_key_dev_service
  AWS_ACCESS_KEY_ID: <AWS_ACCESS_KEY_ID_TEMPORARIA>
  AWS_SECRET_ACCESS_KEY: <AWS_SECRET_ACCESS_KEY_TEMPORARIA>
  AWS_SESSION_TOKEN: <AWS_SESSION_TOKEN_TEMPORARIA>
